# Generated by Django 3.1.5 on 2021-02-11 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Scan Token')),
                ('algorithm', models.CharField(choices=[('NS', 'NOT SET'), ('SVC', 'Simple Support Vector Machine')], default='NS', max_length=10, verbose_name='Algorithm Used')),
            ],
        ),
    ]
