# Generated by Django 3.1.5 on 2021-02-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbackendapp', '0002_scan_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='algorithm',
            field=models.CharField(choices=[('NS', 'NOT SET'), ('SVC', 'Simple C-Support Vector Machine')], default='NS', max_length=10, verbose_name='Algorithm Used'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='token',
            field=models.UUIDField(editable=False, unique=True, verbose_name='Scan Token'),
        ),
    ]
