# Generated by Django 3.1.5 on 2021-02-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbackendapp', '0003_auto_20210214_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='algorithm',
            field=models.CharField(choices=[('SVC', 'Simple C-Support Vector Machine')], default='SVC', max_length=10, verbose_name='Algorithm Used'),
        ),
    ]
