# Generated by Django 3.1.5 on 2021-04-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbackendapp', '0004_auto_20210214_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='image',
            field=models.TextField(default='', editable=False, verbose_name='Image Base64'),
        ),
    ]
