# Generated by Django 3.1.5 on 2021-04-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbackendapp', '0006_scan_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='algorithm',
            field=models.CharField(choices=[('SVC', 'Simple C-Support Vector Machine V1'), ('RAS', 'Residual neural network V18')], default='SVC', max_length=10, verbose_name='Algorithm Used'),
        ),
    ]
