# Generated by Django 3.1.5 on 2021-04-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbackendapp', '0008_auto_20210419_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='algorithm',
            field=models.CharField(choices=[('SVC', 'Simple C-Support Vector Machine V1'), ('RES', 'Residual neural network V18')], default='SVC', max_length=10, verbose_name='Algorithm Used'),
        ),
    ]
